services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: krom-land-administrace-api
    restart: always
    working_dir: /var/www/html/api/
    depends_on:
      - db
    volumes:
      - ../src:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: krom-land-administrace-nginx
    restart: always
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - ../src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: krom-land-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kromland
      MYSQL_USER: kromuser
      MYSQL_PASSWORD: krompassword
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: krom-land-phpmyadmin
    restart: always
    ports:
      - "3010:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
